version: "3"

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "9906:3306"
    environment:
      MYSQL_DATABASE: ludus_service_team
      MYSQL_USER: user_faculdade
      MYSQL_PASSWORD: password_faculdade
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
      
  laravel:
    build: .
    ports:
      - "8100:80"
    depends_on:
      - mysql
    volumes:
      - ./laravel/:/var/www/html
    
volumes: 
  mysql_data:
