# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - teamsludus

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_0f38dfa8f40849bfa9ad8a2eac231bf0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_63e72e8339ca4746bff6b78294d64f4e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0f38dfa8f40849bfa9ad8a2eac231bf0 }}/php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'teamsludus'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d85b5ae0c83946679668299f1d2c5145 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0f38dfa8f40849bfa9ad8a2eac231bf0 }}/php:${{ github.sha }}'